In [16]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
import numpy as np

In [2]:
iris = load_iris()

In [4]:
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target, random_state=42)

In [6]:
clf = GradientBoostingClassifier(learning_rate=0.01, random_state=0)
clf.fit(X_train, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.01, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=0, subsample=1.0, verbose=0,
              warm_start=False)

In [7]:
clf.decision_function(X_test)

array([[-0.52931069,  1.46560359, -0.50448467],
       [ 1.51154215, -0.49561142, -0.50310736],
       [-0.52379401, -0.4676268 ,  1.51953786],
       [-0.52931069,  1.46560359, -0.50448467],
       [-0.53107259,  1.28190451,  0.21510024],
       [ 1.51154215, -0.49561142, -0.50310736],
       [-0.52931069,  1.46560359, -0.50448467],
       [-0.53043817, -0.4676268 ,  1.51953786],
       [-0.52931069,  1.46560359, -0.50448467],
       [-0.52931069,  1.46560359, -0.50448467],
       [-0.53043817, -0.4676268 ,  1.50129926],
       [ 1.51154215, -0.49561142, -0.50310736],
       [ 1.51154215, -0.49561142, -0.50310736],
       [ 1.51154215, -0.49561142, -0.50310736],
       [ 1.51154215, -0.49561142, -0.50310736],
       [-0.52931069,  1.46560359, -0.50448467],
       [-0.52419721, -0.4676268 ,  1.51953786],
       [-0.52931069,  1.46560359, -0.50448467],
       [-0.52931069,  1.46560359, -0.50448467],
       [-0.52419721, -0.4676268 ,  1.51953786],
       [ 1.51154215, -0.49561142, -0.503

In [10]:
np.argmax(clf.decision_function(X_test), axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0], dtype=int64)

In [11]:
clf.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [12]:
clf.predict_proba(X_test)

array([[0.10664722, 0.7840248 , 0.10932798],
       [0.78880668, 0.10599243, 0.10520089],
       [0.10231173, 0.10822274, 0.78946553],
       [0.10664722, 0.7840248 , 0.10932798],
       [0.10825347, 0.66344934, 0.22829719],
       [0.78880668, 0.10599243, 0.10520089],
       [0.10664722, 0.7840248 , 0.10932798],
       [0.10170311, 0.10829611, 0.79000078],
       [0.10664722, 0.7840248 , 0.10932798],
       [0.10664722, 0.7840248 , 0.10932798],
       [0.10317625, 0.10986475, 0.786959  ],
       [0.78880668, 0.10599243, 0.10520089],
       [0.78880668, 0.10599243, 0.10520089],
       [0.78880668, 0.10599243, 0.10520089],
       [0.78880668, 0.10599243, 0.10520089],
       [0.10664722, 0.7840248 , 0.10932798],
       [0.1022747 , 0.1082272 , 0.78949809],
       [0.10664722, 0.7840248 , 0.10932798],
       [0.10664722, 0.7840248 , 0.10932798],
       [0.1022747 , 0.1082272 , 0.78949809],
       [0.78880668, 0.10599243, 0.10520089],
       [0.10588375, 0.11420593, 0.77991032],
       [0.

In [13]:
clf.predict_proba(X_test).sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [14]:
np.argmax(clf.predict_proba(X_test), axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0], dtype=int64)

In [15]:
clf.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [18]:
logreg = LogisticRegression()
named_target = iris.target_names[y_train]
logreg.fit(X_train, named_target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
logreg.classes_

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [20]:
logreg.predict(X_test)

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa', 'setosa', 'setosa',
       'versicolor', 'setosa', 'setosa', 'virginica', 'versicolor',
       'setosa'], dtype='<U10')

In [23]:
arg_max = np.argmax(logreg.decision_function(X_test), axis=1)
arg_max

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0], dtype=int64)

In [24]:
logreg.classes_[arg_max]

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa', 'setosa', 'setosa',
       'versicolor', 'setosa', 'setosa', 'virginica', 'versicolor',
       'setosa'], dtype='<U10')